# utils/slang_dict.py
# Kamus pemetaan kata tidak baku (slang Twitter) ke kata baku medis/umum.
# Digunakan pada tahap normalisasi teks dalam pipeline NLP.

SLANG_MAP = {
    # Singkatan umum Twitter
    "bgt": "banget",
    "bgt": "banget",
    "klo": "kalau",
    "kl": "kalau",
    "klw": "kalau",
    "kalu": "kalau",
    "jg": "juga",
    "juga2": "juga",
    "ga": "tidak",
    "gak": "tidak",
    "ngga": "tidak",
    "nggak": "tidak",
    "ndak": "tidak",
    "g": "tidak",
    "tdk": "tidak",
    "gk": "tidak",
    "tp": "tapi",
    "tpi": "tapi",
    "ttp": "tetap",
    "ttg": "tentang",
    "dr": "dari",
    "utk": "untuk",
    "u": "untuk",
    "mk": "maka",
    "mk": "maka",
    "udh": "sudah",
    "udah": "sudah",
    "sdh": "sudah",
    "dah": "sudah",
    "blm": "belum",
    "blom": "belum",
    "lom": "belum",
    "sm": "sama",
    "sm": "sama",
    "ama": "sama",
    "bs": "bisa",
    "bsa": "bisa",
    "hrs": "harus",
    "msh": "masih",
    "masi": "masih",
    "msih": "masih",
    "lg": "lagi",
    "lg": "lagi",
    "lgi": "lagi",
    "skrg": "sekarang",
    "skrang": "sekarang",
    "skr": "sekarang",
    "krn": "karena",
    "karna": "karena",
    "karna": "karena",
    "krena": "karena",
    "spy": "supaya",
    "biar": "supaya",
    "ckp": "cukup",
    "bnyk": "banyak",
    "byk": "banyak",
    "bngt": "banget",
    "emg": "memang",
    "emang": "memang",
    "mmg": "memang",
    "org": "orang",
    "orng": "orang",
    "tau": "tahu",
    "tw": "tahu",
    "bikin": "membuat",
    "nyebabkan": "menyebabkan",
    "nyebabin": "menyebabkan",
    "pake": "pakai",
    "makan2": "makan",
    "minum2": "minum",
    # Kata slang terkait gejala kesehatan
    "pusinggg": "pusing",
    "pusiingg": "pusing",
    "pusing2": "pusing",
    "muall": "mual",
    "muaalll": "mual",
    "muntahin": "muntah",
    "nyeri2": "nyeri",
    "sakiitt": "sakit",
    "sakittt": "sakit",
    "perihh": "perih",
    "mualll": "mual",
    "kembungg": "kembung",
    "kembungan": "kembung",
    "gerd": "gerd",
    "asam lambung": "asam lambung",
    "magg": "maag",
    "mag": "maag",
    "lambungan": "lambung",
    "obat2": "obat",
    "obatan": "obat",
    "dokter2": "dokter",
    "ngedokter": "ke dokter",
    "periksa2": "periksa",
    "rumsakit": "rumah sakit",
    "rs": "rumah sakit",
    "puskesmas": "puskesmas",
    "klinik": "klinik",
    "apotek": "apotek",
    "apotik": "apotek",
    "resep": "resep",
    "reeseep": "resep",
    "sembuh2": "sembuh",
    "sembuhh": "sembuh",
    "kumat": "kambuh",
    "kumataan": "kambuh",
    "kambuhan": "kambuh",
    "relaps": "kambuh",
    "diet2": "diet",
    "dieting": "diet",
    "pantangan": "pantangan",
    "makanan sehat": "makanan sehat",
    "makan sehat": "makanan sehat",
    "healing": "pemulihan",
    "recover": "pemulihan",
    "recovery": "pemulihan",
    "tips2": "tips",
    "tips&trick": "tips dan trik",
    "info2": "informasi",
    "edukasi": "edukasi",
    "aware": "sadar",
    "awareness": "kesadaran",
}
